FROM node:16.20.2-alpine
RUN apk update && apk add bash && apk add --no-cache coreutils

WORKDIR /usr/src/app

COPY . .
RUN chmod +x ./wait-for-it.sh


RUN npm install

EXPOSE 8000
CMD ["npm", "run", "dev:docker", "--", "--host", "0.0.0.0", "--port", "8000"]