FROM node:16.20.2-alpine
RUN apk update && apk add bash && apk add --no-cache coreutils

WORKDIR /usr/src/app

COPY . .
RUN chmod +x ./wait-for-it.sh


RUN npm install
ENV DATABASE_URL=postgres://webapp:secret@host.docker.internal:5432/postgres

EXPOSE 1337
CMD ["npm", "run", "start:test"]