FROM node:16.20.2-alpine
RUN apk update && apk add bash && apk add --no-cache coreutils


FROM mcr.microsoft.com/playwright:v1.44.0-jammy

WORKDIR /usr/src/app

COPY . .
RUN chmod +x ./wait-for-it.sh

RUN npm install

ENV CI=true

CMD ["npm", "run", "test"]